# Generated by Django 4.2 on 2024-11-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
